on: pull_request
name: Test
jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination:
            - -scheme "Loop-iOS" -destination "platform=iOS Simulator,name=iPhone 11 Pro"
            - -scheme "Loop-tvOS" -destination "platform=tvOS Simulator,name=Apple TV 4K"
            - -scheme "Loop-iOS" -destination "platform=macOS,variant=Mac Catalyst"
            - -scheme "Loop-macOS" -destination "platform=macOS,arch=x86_64"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependency Cache
        uses: actions/cache@v1
        id: dependency-cache
        with:
          path: Carthage/Checkouts
          key: carthage-${{ hashFiles('Cartfile.resolved') }}
      - name: Pull Dependencies If Needed
        if: steps.dependency-cache.outputs.cache-hit != 'true'
        run: |
          carthage checkout
      - name: Test via xcodebuild
        run: |
          xcodebuild clean test -workspace Loop.xcworkspace ${{ matrix.destination }} CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES
